### ISSUE TITLE
Error: Element type is invalid: expected a string but got: object.

### ISSUE THREAD

**Issue by JaePhoenix** [Tomekmularczyk/react-intl-context-provider#1]
This might be my issue, but i cannot seem to figure it out.

My issue is with the LanguageSwitcher.
I seem to be running into the following error when using <IntlConsumer>

```Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.```

As soon as I remove the component tags, the page works, but the switching of languages does not work.

Here is my code for my Navigtion page:
```
import React from "react";
import { IntlConsumer } from './IntlContext';
import translation from './Translations';

const LanguageSwitcher = () => (
   <IntlConsumer>
      {({ updateProps, ...providerProps }) => (
       <div>
          <button onClick={() => updateProps({ locale: "en", messages: translation['en'] })}>
            English
          </button>
          <button onClick={() => updateProps({ locale: "pt", messages: translation['pt'] })}>
            Portuguese
          </button>
        </div>
      )}
    </IntlConsumer>
  );
```

Then eventually calling it in my nav
`<LanguageSwitcher />`

What am I missing?

**Comment by Tomekmularczyk** [comment]
@JaePhoenix could you share a repo with such problem?

**Comment by JaePhoenix** [comment]
Fixed code section to lookHi T like code

**Comment by JaePhoenix** [comment]
Hi @Tomekmularczyk.  Thank you so much for the assistance.

You can look at https://github.com/JaePhoenix/test-languageSwitch-react.

Just run npm install, gatsby build, npm run develop.

**Comment by Tomekmularczyk** [comment]
@JaePhoenix this repository is empty :)

**Comment by JaePhoenix** [comment]
HAHA!  Oh no, I forgot to push.  Just did.  Could you please check again?

**Comment by Tomekmularczyk** [comment]
@JaePhoenix the problem is that Gatsby v1 is using its own version of React internally - 15.6.1 in this case.

In version v2 they have moved React as a [peer dependency](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json#L174). So in order to use new React Context API you would have to migrate to V2.

**Comment by JaePhoenix** [comment]
Wow! That opens up a whole new can of worms.  Thank you so much for the assistance.
